USE csit115;

CREATE TABLE EMPLOYEE(
	name VARCHAR(30) NOT NULL,
    address VARCHAR(100) NOT NULL,
    phone VARCHAR(20) NOT NULL,
CONSTRAINT DEPT_PK PRIMARY KEY (name) );

INSERT INTO EMPLOYEE VALUES ('Peter Smith', '12 Hillcrest Street, Wollongong', '0421234567');

SELECT * FROM EMPLOYEE;

DROP TABLE EMPLOYEE;
