/* DML for Task 3														*/

INSERT INTO EMPLOYEE VALUES( 21, 'Mary', 'P', 'Doe', '1978-01-13', 15, 'Station St.', 'Horsley', 'NSW', 2530 );
INSERT INTO EMPLOYEE VALUES( 22, 'Janusz', 'R', 'Getta', '1916-01-01', 10, 'Ellenborough Pl.', 'Horsley', 'NSW', 2530 );

INSERT INTO ADMIN VALUES( 21, 'PROGRAMMER' );
INSERT INTO ADMIN VALUES( 22, 'DBA' );

DELETE FROM ADMIN WHERE ENUM = 20;

DELETE FROM EMPLOYEE WHERE ENUM = 20;

UPDATE ADMIN SET POSITION = 'BOSS' WHERE ENUM =  18;

/* DML and DDL for Task 4													*/

CREATE TABLE MESSAGE( mbody VARCHAR(25), CONSTRAINT MESSAGE_PKEY PRIMARY KEY (mbody) );

INSERT INTO MESSAGE( 'Hello world !!!' );
COMMIT;

ALTER TABLE MESSAGE MODIFY mbody VARCHAR(50);

UPDATE MESSAGE SET mbody = 'Hello myworld !!!' WHERE mbody LIKE 'Hello%';

/* UPDATE EMPLOYEE
   SET INITIALS = 'X'
   WHERE INITIALS IS NULL */

ROLLBACK;

DELETE FROM ADMIN WHERE ENUM < 18;

DROP TABLE MESSAGE;

COMMIT;
