/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package labone;

public class PolicyException extends Exception {
    private int ID;

    public PolicyException(int ID) throws PolicyException {
        this.ID = ID;
    }
    public String toString() {
        return "The Policy ID was not valid and a new ID (the generated ID) is generated by admin and assigned for the policy";
    }
    public int getID() {
        return ID;
    }
}