spool solution1;
set echo on;
set feedback on;
set linesize 100;
set pagesize 200;

ALTER TABLE EMPLOYEE
ADD TOTAL_ORDERS NUMBER(5) DEFAULT(NULL);

UPDATE EMPLOYEE
SET TOTAL_ORDERS =
(SELECT COUNT(EMPLOYEE_ID)
FROM ORDERS 
WHERE EMPLOYEE.EMPLOYEE_ID = ORDERS.EMPLOYEE_ID);

UPDATE EMPLOYEE
SET TOTAL_ORDERS = 0
WHERE TOTAL_ORDERS = NULL;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT CHK_TOTAL CHECK (TOTAL_ORDERS IS NOT NULL);

CREATE TABLE CUSTOMER_COUNTRIES AS
    SELECT COUNTRY, COUNT(CUSTOMER_CODE) AS CUSTOMERS
    FROM CUSTOMER
    GROUP BY COUNTRY;
    
ALTER TABLE CUSTOMER_COUNTRIES
ADD CONSTRAINT PK_COUNTRY PRIMARY KEY (COUNTRY);

ALTER TABLE CUSTOMER_COUNTRIES
ADD CONSTRAINT CHK_CUSTOMERS CHECK (CUSTOMERS IS NOT NULL);

spool off;