use csit115;

CREATE TABLE BRANCH(
BNAME VARCHAR(20) NOT NULL,
BLDG INT(10) NOT NULL,
STREET VARCHAR(20) NOT NULL,
CITY VARCHAR(20) NOT NULL,
TOTALEMP INT(10) NOT NULL,
CONSTRAINT BRANCH_PKEY PRIMARY KEY(BNAME),
CONSTRAINT BRANCH_CK1 UNIQUE KEY(BLDG, STREET, CITY),
CONSTRAINT BRANCH_CHECK1 CHECK(BLDG BETWEEN 0 AND 1000),
CONSTRAINT BRANCH_CHECK2 CHECK(TOTALEMP BETWEEN 0 AND 100)
);

CREATE TABLE EMPLOYEE(
BNAME VARCHAR(50) NOT NULL,
EMPNUM INT(6) NOT NULL,
FNAME VARCHAR(40) NOT NULL,
LNAME VARCHAR(40) NOT NULL,
DOB DATE NOT NULL,
POSITION VARCHAR(40) NOT NULL,
CONSTRAINT EMPLOYEE_PKEY PRIMARY KEY(BNAME, EMPNUM),
CONSTRAINT EMPLOYEE_CK1 UNIQUE KEY(FNAME, LNAME, DOB),
CONSTRAINT EMPLOYEE_FKEY FOREIGN KEY(BNAME) REFERENCES BRANCH(BNAME),
CONSTRAINT EMPLOYEE_CHECK1 CHECK(EMPNUM BETWEEN 100000 AND 999999)
);

CREATE TABLE CLIENTS(
PHNUM CHAR(10) NOT NULL,
FNAME VARCHAR(40) NOT NULL,
LNAME VARCHAR(40) NOT NULL,
CLIENTTYPE VARCHAR(5) NOT NULL,
BNAME VARCHAR(50) NOT NULL,
AGENTNUM INT(6) NOT NULL,
CONSTRAINT CLIENT_PKEY PRIMARY KEY(PHNUM),
CONSTRAINT CLIENT_FKEY FOREIGN KEY(BNAME, AGENTNUM) REFERENCES EMPLOYEE(BNAME, EMPNUM),
CONSTRAINT CLIENT_CHECK1 CHECK(CLIENTTYPE IN ('Buyer', 'Owner')),
CONSTRAINT CLIENT_CHECK2 CHECK(LENGTH(PHNUM) = 10)
);

CREATE TABLE PROPERTY(
LOTNUM INT(10) NOT NULL,
STREET VARCHAR(50) NOT NULL,
CITY VARCHAR(50) NOT NULL,
ASKINGPRICE REAL(8,2) NOT NULL,
OWNERPH CHAR(10) NOT NULL,
CONSTRAINT PROPERTY_PKEY PRIMARY KEY(LOTNUM, STREET, CITY),
CONSTRAINT PROPERTY_FKEY FOREIGN KEY(OWNERPH) REFERENCES CLIENTS(PHNUM),
CONSTRAINT PROPERTY_CHECK1 CHECK(ASKINGPRICE BETWEEN 0.00 AND 99999999.99)
);

CREATE TABLE OFFER(
CLIENTPH CHAR(10) NOT NULL,
LOTNUM INT(255) NOT NULL,
STREET VARCHAR(50) NOT NULL,
CITY VARCHAR(50) NOT NULL,
OFFERDATE DATE NOT NULL,
MINPRICE REAL(8,2) NOT NULL,
MAXPRICE REAL(8,2) NOT NULL,
CONSTRAINT OFFER_PKEY PRIMARY KEY(CLIENTPH, LOTNUM, STREET, CITY, OFFERDATE),
CONSTRAINT OFFER_FKEY1 FOREIGN KEY(CLIENTPH) REFERENCES CLIENTS(PHNUM),
CONSTRAINT OFFER_FKEY2 FOREIGN KEY(LOTNUM, STREET, CITY) REFERENCES PROPERTY(LOTNUM, STREET, CITY),
CONSTRAINT OFFER_CHECK1 CHECK(MINPRICE > 0.00 AND MINPRICE < 99999999.99),
CONSTRAINT OFFER_CHECK2 CHECK(MAXPRICE > 0.00 AND MAXPRICE < 99999999.99)
);